export const success = 'FETCH_CART_SUCCESS'
export const load = 'FETCH_CART_LOAD'
export const failure = 'FETCH_CART_FAILURE'
export const addToOrder = 'CARTS_ADD_TO_ORDER'
export const deteleOfOrder = 'CARTS_DELETE_OF_ORDER'